filter:
    paths: [src/*]
    excluded_paths: [bin/*, spec/*, tests/*, stub/*, coverage/*]
checks:
  php:
    code_rating: true
    duplication: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true
tools:
  php_code_coverage: true
  php_code_sniffer:
    config:
      standard: PSR2
    filter:
      paths: ['src']
  php_loc:
    enabled: true
    excluded_dirs: [vendor, spec, stubs]
  php_sim: false
build:
  environment:
    php:
      version: 5.6
  dependencies:
    before:
      - composer --version
      - composer global require "fxp/composer-asset-plugin:@dev"
      - composer update
  tests:
    override:
      -
        command: 'composer test-coverage'
        coverage:
          file: 'tests/codeception/_output/coverage.xml'
          format: 'clover'
